export const SET_PATHS_LIST = 'SET_PATHS_LIST';
export const SET_PATHS_CODE = 'SET_PATHS_CODE';
export const SET_IS_FETCHING_PATHS_DATA = 'SET_IS_FETCHING_PATHS_DATA';
export const CLEAR_PATHS_DATA = 'CLEAR_PATHS_DATA';