export const SET_QUESTIONS = 'SET_QUESTION';
export const SET_GAME_CODE = 'SET_GAME_CODE';
export const SET_IS_FETCHING_GAME_DATA = 'SET_IS_FETCHING_GAME_DATA';
export const CLEAR_GAME_DATA = 'CLEAR_GAME_DATA';