export const SET_DAILY_GRAPH_DATA = 'SET_DAILY_GRAPH_DATA';
export const SET_MONTHLY_GRAPH_DATA = 'SET_MONTHLY_GRAPH_DATA';
export const SET_TABLE_DATA = 'SET_TABLE_DATA';
export const SET_PERFORMANCE_CODE = 'SET_PERFORMANCE_DATA';
export const SET_IS_FETCHING_PERFORMANCE_DATA = 'SET_IS_FETCHING_PERFORMANCE_DATA';
export const CLEAR_PERFORMANCE_DATA = 'CLEAR_PERFORMANCE_DATA';