export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_AUTHENTICATION_CODE = 'SET_AUTHENTICATION_CODE';
export const SET_IS_FETCHING_AUTHENTICATION = 'SET_IS_FETCHING_AUTHENTICATING';
export const CLEAR_AUTHENTICATION_DATA = 'CLEAR_AUTHENTICATION_DATA';
export const SET_REWARDFUL_ID = 'SET_REWARDFUL_ID'