export const SET_EVENTS = 'SET_EVENTS';
export const SET_IS_FETCHING_EVENTS = 'SET_IS_FETCHING_EVENTS';
export const SET_IS_FETCHING_CARDS = 'SET_IS_FETCHING_CARDS';
export const SET_CONTENT_SPOTLIGHT = 'SET_CONTENT_SPOTLIGHT';
export const SET_WEEKLY_HAND_BREAKDOWN = 'SET_WEEKLY_HAND_BREAKDOWN';