name: Deploy to Firebase Hosting For Development

'on':
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.0
      - name: create .env
        run: |
          mv .env.dev .env
      - run: npm i && npm run build-github
      - name: target the project in firebase
        run: firebase use devenvclc
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ secrets.DEVENVCLC_ACCOUNT }}
          projectId: devenvclc
